name: PR Checkpoint  # Name of the workflow that will appear in the Action Tab 
run-name: ${{ github.actor }} is creating PR  # this one will show if you click the action tab in the left side. like list, basta ganon.
on:  # ito trigger to kung kelan gagana like if you specify pr or in push but pwede both
    pull_request:  
        types: [opened, synchronize, reopened]
    push: 
        branches:  # branch which this one is main 
            - main
jobs:  # ito pang group ng jobs specify to kung ano mga gagawin
    type-check:
        runs-on: ubuntu-latest  # anong virtual server yung trip mong i run itong workflow
        steps:  # steps na mga gagawin ng job
            - name: Checkout   # name ng isang job 
              uses: actions/checkout@v4  # anong actions version latest ata v4 wala pang v5 eh

            - name: Setup Node (pnpm with cache)  
              uses: actions/setup-node@v4
              with:   
                node-version: '22'
                cache: 'pnpm'
                cache-dependency-path: '**/pnpm-locl.yaml'
             
            - name: Enable corepack & activate pnpm
              run: |
                corepack enable
                # pick a pnpm version you want; optional: use 'latest'
                corepack prepare pnpm@8.10.0 --activate
            
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

              # typescript
            - name: Type check (Typescript)
              run: pnpm run typecheck
            
              # checking the lint 
            - name: lint
              run: pnpm run lint

            - name: Build
              if: ${{ success() }}
              run: pnpm build