name: PR Checkpoint  # Name of the workflow that will appear in the Action Tab 
run-name: ${{ github.actor }} is creating PR  # this one will show if you click the action tab in the left side. like list, basta ganon.
on:  # ito trigger to kung kelan gagana like if you specify pr or in push but pwede both
    pull_request:  
        types: [opened, synchronize, reopened]
    push: 
        branches:  # branch which this one is main 
            - main
jobs:  # ito pang group ng jobs specify to kung ano mga gagawin
    type-check:
        runs-on: ubuntu-latest  # anong virtual server yung trip mong i run itong workflow
        steps:  # steps na mga gagawin ng job
            - name: Checkout   # name ng isang job 
              uses: actions/checkout@v4  # anong actions version latest ata v4 wala pang v5 eh

            - name: Setup Node (pnpm with cache)  
              uses: actions/setup-node@v4
              with:   
                node-version: '22'
                # cache: 'pnpm'
                # cache-dependency-path: '**/pnpm-lock.yaml'
  
                
            - name: Setup pnpm (install pnpm on runner)
              uses: pnpm/action-setup@v2
              with:
                version: 9.0

            # - name: Enable corepack & activate pnpm
            #   run: |
            #     corepack enable 
            #     corepack prepare pnpm@8.10.0 --activate
            #     pnpm -v
            
            - name: Install dependencies
              run: pnpm install

              # typescript
            # - name: Type check (Typescript)
            #   run: pnpm -w run typecheck

              # checking the lint 
            - name: lint
              run: pnpm run lint

            - name: Build
              if: ${{ success() }}
              run: pnpm run build